from __future__ import annotations

import io
import os
import random
from importlib.metadata import version
from pathlib import Path

from PIL import Image, features

from wsj_embeddings.adapters import JinaEmbeddingAdapter
from wsj_embeddings.catalog import configuration_id
from wsj_embeddings.image_rendition import (
    MAX_HOSTED_IMAGE_BYTES,
    PRODUCTION_IMAGE_TRANSFORM_ID,
    SOURCE_BYTES_TRANSFORM_ID,
    PillowImageCodec,
    install_image_rendition,
    prepare_image_input,
)


class _GeneratedTokenizer:
    def token_offsets(self, text: str) -> tuple[tuple[int, int], ...]:
        return tuple((index, index + 1) for index in range(len(text)))


def _png(mode: str, size: tuple[int, int], data: bytes | tuple[int, ...]) -> bytes:
    output = io.BytesIO()
    image = (
        Image.frombytes(mode, size, data)
        if isinstance(data, bytes)
        else Image.new(mode, size, data)
    )
    image.save(output, format="PNG", compress_level=0)
    return output.getvalue()


def test_pinned_production_pillow_codec_binds_profile_and_prepares_both_paths(
    tmp_path: Path,
) -> None:
    """Exercise the installed production decoder and encoder with generated bytes."""

    assert version("Pillow") == "11.3.0"
    assert version("tokenizers") == "0.21.4"

    codec = PillowImageCodec()
    expected_build_suffix = (
        f"-build-jpeg-{features.version_codec('jpg')}"
        f"-turbo-{features.version_feature('libjpeg_turbo')}"
        f"-zlib-{features.version_codec('zlib')}"
        f"-webp-{features.version_module('webp')}"
    )
    assert codec.transform_id == PRODUCTION_IMAGE_TRANSFORM_ID + expected_build_suffix

    adapter = JinaEmbeddingAdapter(
        environment={"JINA_API_KEY": "generated-fixture-key"},
        tokenizer=_GeneratedTokenizer(),
    )
    unbound_configuration = configuration_id(adapter.profile)
    adapter.bind_image_codec(codec)
    assert adapter.image_codec is codec
    assert adapter.profile.image_transform == codec.transform_id
    assert configuration_id(adapter.profile) != unbound_configuration

    source = _png("RGBA", (4, 3), (10, 20, 30, 128))
    passthrough = prepare_image_input(
        source,
        codec=codec,
        expected_input_rules=codec.input_rules,
        expected_transform_id=codec.transform_id,
    )
    assert passthrough.data == source
    assert passthrough.transform_id == SOURCE_BYTES_TRANSFORM_ID
    assert passthrough.rendition_relative_path is None

    random_pixels = random.Random(0).randbytes(1_400 * 1_400 * 3)
    oversized = _png("RGB", (1_400, 1_400), random_pixels)
    assert len(oversized) > MAX_HOSTED_IMAGE_BYTES
    output_descriptor = os.open(tmp_path, os.O_RDONLY | os.O_DIRECTORY)
    try:
        derived = prepare_image_input(
            oversized,
            codec=codec,
            expected_input_rules=codec.input_rules,
            expected_transform_id=codec.transform_id,
            install_rendition=lambda data, info, digest: install_image_rendition(
                output_descriptor,
                data,
                info,
                digest,
                transform_id=codec.transform_id,
                codec=codec,
            ),
        )
    finally:
        os.close(output_descriptor)

    assert derived.transform_id == codec.transform_id
    assert derived.embedded_info.format == "JPEG"
    assert len(derived.data) <= MAX_HOSTED_IMAGE_BYTES
    assert derived.rendition_relative_path is not None
    rendition_bytes = (
        tmp_path / Path(derived.rendition_relative_path)
    ).read_bytes()
    assert rendition_bytes == derived.data
